//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TypegeistDataSet", "ClientResultResultStatement", "ClientResult", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Typegeist.Server.Data.ClientResult), "ResultStatement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Typegeist.Server.Data.ResultStatement), true)]

#endregion

namespace Typegeist.Server.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TypegeistDataSetContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TypegeistDataSetContainer object using the connection string found in the 'TypegeistDataSetContainer' section of the application configuration file.
        /// </summary>
        public TypegeistDataSetContainer() : base("name=TypegeistDataSetContainer", "TypegeistDataSetContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TypegeistDataSetContainer object.
        /// </summary>
        public TypegeistDataSetContainer(string connectionString) : base(connectionString, "TypegeistDataSetContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TypegeistDataSetContainer object.
        /// </summary>
        public TypegeistDataSetContainer(EntityConnection connection) : base(connection, "TypegeistDataSetContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Workunit> Workunits
        {
            get
            {
                if ((_Workunits == null))
                {
                    _Workunits = base.CreateObjectSet<Workunit>("Workunits");
                }
                return _Workunits;
            }
        }
        private ObjectSet<Workunit> _Workunits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClientResult> ClientResults
        {
            get
            {
                if ((_ClientResults == null))
                {
                    _ClientResults = base.CreateObjectSet<ClientResult>("ClientResults");
                }
                return _ClientResults;
            }
        }
        private ObjectSet<ClientResult> _ClientResults;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ResultStatement> ResultStatements
        {
            get
            {
                if ((_ResultStatements == null))
                {
                    _ResultStatements = base.CreateObjectSet<ResultStatement>("ResultStatements");
                }
                return _ResultStatements;
            }
        }
        private ObjectSet<ResultStatement> _ResultStatements;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Workunits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkunits(Workunit workunit)
        {
            base.AddObject("Workunits", workunit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientResults EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientResults(ClientResult clientResult)
        {
            base.AddObject("ClientResults", clientResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ResultStatements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResultStatements(ResultStatement resultStatement)
        {
            base.AddObject("ResultStatements", resultStatement);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TypegeistDataSet", Name="ClientResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClientResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClientResult object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="returnTime">Initial value of the ReturnTime property.</param>
        public static ClientResult CreateClientResult(global::System.Guid guid, global::System.String url, global::System.DateTime returnTime)
        {
            ClientResult clientResult = new ClientResult();
            clientResult.Guid = guid;
            clientResult.Url = url;
            clientResult.ReturnTime = returnTime;
            return clientResult;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReturnTime
        {
            get
            {
                return _ReturnTime;
            }
            set
            {
                OnReturnTimeChanging(value);
                ReportPropertyChanging("ReturnTime");
                _ReturnTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnTime");
                OnReturnTimeChanged();
            }
        }
        private global::System.DateTime _ReturnTime;
        partial void OnReturnTimeChanging(global::System.DateTime value);
        partial void OnReturnTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TypegeistDataSet", "ClientResultResultStatement", "ResultStatement")]
        public EntityCollection<ResultStatement> ResultStatements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ResultStatement>("TypegeistDataSet.ClientResultResultStatement", "ResultStatement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ResultStatement>("TypegeistDataSet.ClientResultResultStatement", "ResultStatement", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TypegeistDataSet", Name="FontFallbackStatement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FontFallbackStatement : ResultStatement
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FontFallbackStatement object.
        /// </summary>
        /// <param name="clientResultGuid">Initial value of the ClientResultGuid property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="fontFallback">Initial value of the FontFallback property.</param>
        /// <param name="count">Initial value of the Count property.</param>
        public static FontFallbackStatement CreateFontFallbackStatement(global::System.Guid clientResultGuid, global::System.Guid guid, global::System.String fontFallback, global::System.Int32 count)
        {
            FontFallbackStatement fontFallbackStatement = new FontFallbackStatement();
            fontFallbackStatement.ClientResultGuid = clientResultGuid;
            fontFallbackStatement.Guid = guid;
            fontFallbackStatement.FontFallback = fontFallback;
            fontFallbackStatement.Count = count;
            return fontFallbackStatement;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FontFallback
        {
            get
            {
                return _FontFallback;
            }
            set
            {
                OnFontFallbackChanging(value);
                ReportPropertyChanging("FontFallback");
                _FontFallback = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FontFallback");
                OnFontFallbackChanged();
            }
        }
        private global::System.String _FontFallback;
        partial void OnFontFallbackChanging(global::System.String value);
        partial void OnFontFallbackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private global::System.Int32 _Count;
        partial void OnCountChanging(global::System.Int32 value);
        partial void OnCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TypegeistDataSet", Name="ResultStatement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(FontFallbackStatement))]
    public abstract partial class ResultStatement : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ClientResultGuid
        {
            get
            {
                return _ClientResultGuid;
            }
            set
            {
                OnClientResultGuidChanging(value);
                ReportPropertyChanging("ClientResultGuid");
                _ClientResultGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientResultGuid");
                OnClientResultGuidChanged();
            }
        }
        private global::System.Guid _ClientResultGuid;
        partial void OnClientResultGuidChanging(global::System.Guid value);
        partial void OnClientResultGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TypegeistDataSet", "ClientResultResultStatement", "ClientResult")]
        public ClientResult ClientResult
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientResult>("TypegeistDataSet.ClientResultResultStatement", "ClientResult").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientResult>("TypegeistDataSet.ClientResultResultStatement", "ClientResult").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ClientResult> ClientResultReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientResult>("TypegeistDataSet.ClientResultResultStatement", "ClientResult");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ClientResult>("TypegeistDataSet.ClientResultResultStatement", "ClientResult", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TypegeistDataSet", Name="Workunit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Workunit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Workunit object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static Workunit CreateWorkunit(global::System.Guid guid, global::System.String url)
        {
            Workunit workunit = new Workunit();
            workunit.Guid = guid;
            workunit.Url = url;
            return workunit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion
    
    }

    #endregion
    
}
